# This workflow is heavily inspired by https://github.com/nlohmann/json/blob/develop/.github/workflows/windows.yml
name: Windows Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, x86]

    steps:
      - uses: actions/checkout@v2
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.architecture }}
      - name: cmake
        run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
      - name: build
        run: cmake --build build --parallel 10
      - name: test
        run: cd build ; ctest -j 10 -C Debug --output-on-failure

  msvc2019:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build -G "Visual Studio 16 2019" -A ${{ matrix.architecture }}
    - name: build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 10
    - name: test
      run: cd build ; ctest -j 10 -C ${{ matrix.build_type }} --output-on-failure

  msvc2019_latest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -S . -B build -G "Visual Studio 16 2019" -DCMAKE_CXX_FLAGS="/std:c++latest"
    - name: build
      run: cmake --build build --config Release --parallel 10
    - name: test
      run: cd build ; ctest -j 10 -C Release --output-on-failure

  clang:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [10, 11]

    steps:
      - uses: actions/checkout@v2
      - name: install Clang
        run: curl -fsSL -o LLVM${{ matrix.version }}.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ matrix.version }}.0.0/LLVM-${{ matrix.version }}.0.0-win64.exe ; 7z x LLVM${{ matrix.version }}.exe -y -o"C:/Program Files/LLVM"
      - name: cmake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang++.exe" -G"MinGW Makefiles"
      - name: build
        run: cmake --build build --parallel 10
      - name: test
        run: cd build ; ctest -j 10 -C Debug --output-on-failure

  clang-cl-11:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [Win32, x64]

    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} -T ClangCL
      - name: build
        run: cmake --build build --config Debug --parallel 10
      - name: test
        run: cd build ; ctest -j 10 -C Debug --output-on-failure